export const FETCH_USER = 'FETCH_USER';

export const FETCH_LOG = 'FETCH_LOG';
export const UPDATE_LOG = 'UPDATE_LOG';
export const ADD_LOG = 'ADD_LOG';

export const SET_DATE = 'SET_DATE';

export const ADD_MEAL = 'ADD_MEAL';
export const FETCH_MEALS = 'FETCH_MEALS';
export const FETCH_MEAL = 'FETCH_MEAL';

export const FETCH_LOGGED_FOODS = 'FETCH_LOGGED_FOODS';
export const CLEAR_LOGGED_FOODS = 'CLEAR_LOGGED_FOODS';
export const ADD_LOGGED_FOOD = 'ADD_LOGGED_FOOD';
export const DELETE_LOGGED_FOODS = 'DELETE_LOGGED_FOODS';
export const DELETE_LOGGED_FOOD = 'DELETE_LOGGED_FOOD';

export const FETCH_USDA_FOODS = 'FETCH_USDA_FOODS';
export const FETCH_USDA_FOODS_CANCEL = 'FETCH_USDA_FOODS_CANCEL';
export const FETCH_USDA_FOODS_NEXT_PAGE = 'FETCH_USDA_FOODS_NEXT_PAGE';
export const FETCH_DETAILED_USDA_FOOD = 'FETCH_DETAILED_FOOD';
export const SELECT_FOOD = 'SELECT_FOOD';

export const FETCH_CUSTOM_FOODS = 'FETCH_CUSTOM_FOODS';
export const FETCH_CUSTOM_FOODS_NEXT_PAGE = 'FETCH_CUSTOM_FOODS_NEXT_PAGE';
export const FETCH_DETAILED_CUSTOM_FOOD = 'FETCH_DETAILED_CUSTOM_FOOD';
export const SELECT_CUSTOM_FOOD = 'SELECT_CUSTOM_FOOD';

export const CLEAR_DETAILED_FOOD = 'CLEAR_DETAILED_FOOD';
export const CLEAR_USDA_FOODS = 'CLEAR_FOODS';
export const CLEAR_CUSTOM_FOODS = 'CLEAR_CUSTOM_FOODS';

export const DELETE_MEAL = 'DELETE_MEAL';
export const EDIT_MEAL_NAME = 'EDIT_MEAL_NAME';

export const SELECT_LOGGED_FOOD = 'SELECT_LOGGED_FOOD';
export const RESET_SELECT_LOGGED_FOOD = 'RESET_SELECT_LOGGED_FOOD';
export const COPY_LOGGED_FOOD = 'COPY_LOGGED_FOOD';
export const CLEAR_COPIED_FOOD = 'CLEAR_COPIED_FOOD';
export const PASTE_LOGGED_FOOD = 'PASTE_LOGGED_FOOD';

export const SET_WEIGHT_VALUE = 'SELECT_FOOD';

export const ADD_CUSTOM_FOOD = 'ADD_CUSTOM_FOOD';
export const DELETE_CUSTOM_FOOD = 'DELETE_CUSTOM_FOOD';

export const UPDATE_USER_NUTRIENT_TARGETS = 'UPDATE_USER_NUTRIENT_TARGETS';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
